# Generated by Django 5.0.3 on 2024-03-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96)),
                ('is_correct', models.BooleanField(default=False)),
                ('img', models.ImageField(blank=True, null=True, upload_to='quiz/img_options/')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=48)),
                ('description', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('img_preview', models.ImageField(upload_to='quiz/')),
                ('img_bg', models.ImageField(upload_to='quiz/')),
                ('visibility', models.IntegerField(choices=[(0, 'Все'), (1, 'Магнезиус'), (2, 'Музей Магнезит')], default=0)),
                ('category', models.IntegerField(choices=[(0, 'Детская'), (1, 'Взрослая')], default=0)),
                ('ask_name', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=96)),
                ('description', models.TextField(blank=True, null=True)),
                ('visible', models.BooleanField(default=False)),
                ('question_type', models.IntegerField(choices=[(0, 'Один вариант ответа'), (1, 'Несколько вариантов ответа'), (2, 'Выбор изображения'), (3, 'Пазл')], default=0)),
                ('correct_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_option', to='quiz.option')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
